# Generated by Django 5.1.3 on 2025-12-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="photo_file_id",
            field=models.CharField(
                blank=True,
                help_text="Telegram photo file ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
