# Generated by Django 5.1.3 on 2025-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_shop_photo_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="latitude",
            field=models.FloatField(blank=True, help_text="Shop latitude", null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="longitude",
            field=models.FloatField(blank=True, help_text="Shop longitude", null=True),
        ),
    ]
