# Generated by Django 5.1.3 on 2025-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0003_shop_latitude_shop_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_approved",
            field=models.BooleanField(default=False, help_text="Admin approved"),
        ),
    ]
