# Generated by Django 5.1.3 on 2025-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_shop_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ['order', 'name_uz'], 'verbose_name': 'Car Brand', 'verbose_name_plural': 'Car Brands'},
        ),
        migrations.RemoveField(
            model_name='carbrand',
            name='name',
        ),
        migrations.AddField(
            model_name='carbrand',
            name='name_ru',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbrand',
            name='name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
