# Generated by Django 5.1.3 on 2025-12-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_carbrand_options_remove_carbrand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='part_categories_ru',
            field=models.JSONField(blank=True, help_text='Part categories in Russian', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='part_categories_uz',
            field=models.JSONField(blank=True, help_text='Part categories in Uzbek', null=True),
        ),
    ]
