# Generated by Django 5.1.3 on 2026-01-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0006_shop_part_categories_ru_shop_part_categories_uz"),
    ]

    operations = [
        migrations.CreateModel(
            name="UstaXona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="Service center latitude", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="Service center longitude", null=True
                    ),
                ),
                (
                    "photo_file_id",
                    models.CharField(
                        blank=True,
                        help_text="Telegram photo file ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "service_types_uz",
                    models.JSONField(
                        blank=True, help_text="Service types in Uzbek", null=True
                    ),
                ),
                (
                    "service_types_ru",
                    models.JSONField(
                        blank=True, help_text="Service types in Russian", null=True
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, help_text="Admin approved"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_brands",
                    models.ManyToManyField(
                        related_name="usta_xonalar", to="django_app.carbrand"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usta_xonalar",
                        to="django_app.city",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usta_xonalar",
                        to="django_app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usta Xona",
                "verbose_name_plural": "Usta Xonalar",
                "db_table": "usta_xonalar",
            },
        ),
    ]
